FROM ghcr.io/ublue-os/kinoite-main:latest

## Other possible base images include:
# FROM ghcr.io/ublue-os/bazzite:stable
# FROM ghcr.io/ublue-os/bluefin-nvidia:stable
# 
# ... and so on, here are more base images
# Universal Blue Images: https://github.com/orgs/ublue-os/packages
# Fedora base image: quay.io/fedora/fedora-bootc:41
# CentOS base images: quay.io/centos-bootc/centos-bootc:stream10

### MODIFICATIONS
## make modifications desired in your image and install packages by modifying the build.sh script
## the following RUN directive does all the things required to run "build.sh" as recommended.

COPY editions/plasma/nova-plasma/build.sh /tmp/build.sh
COPY scripts/dx/build-dx.sh /tmp/build-dx.sh
COPY scripts/shared/build-shared.sh /tmp/build-shared.sh
COPY files/shared /
COPY files/plasma/shared /
COPY files/plasma/dx/os-release /etc

RUN mkdir -p /var/lib/alternatives && \
    echo "nova_plasma_dx" >> /usr/share/nova/image_type && \
    /tmp/build.sh && \
    /tmp/build-shared.sh && \
    /tmp/build-dx.sh && \
    ostree container commit
